using System;
using Office = Microsoft.Office.Core;
using UpslideClone.Core.Util;
using UpslideClone.Excel.Ribbon;

namespace UpslideClone.Excel
{
    /// <summary>
    /// Excel VSTO add-in entry point (user-editable half of the partial class).
    /// The matching ThisAddIn.Designer.cs is generated by the Visual Studio
    /// "Excel VSTO Add-in" template — see src\UpslideClone.Excel\README.md.
    /// </summary>
    public partial class ThisAddIn
    {
        private void ThisAddIn_Startup(object sender, EventArgs e)
        {
            Logger.Info("UpslideClone.Excel add-in started.");
            // W2: register keyboard shortcuts via Application.OnKey from ShortcutMap.
        }

        private void ThisAddIn_Shutdown(object sender, EventArgs e)
        {
            Logger.Info("UpslideClone.Excel add-in shutting down.");
        }

        /// <summary>Serve the Upslide ribbon via Ribbon XML (not the designer).</summary>
        protected override Office.IRibbonExtensibility CreateRibbonExtensibilityObject()
        {
            return new UpslideRibbon();
        }

        #region VSTO generated code
        /// <summary>Required method for Designer support — do not modify with the code editor.</summary>
        private void InternalStartup()
        {
            this.Startup += new EventHandler(ThisAddIn_Startup);
            this.Shutdown += new EventHandler(ThisAddIn_Shutdown);
        }
        #endregion
    }
}
